name: Publish Extension

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Parse tag for package and version
        id: parse_tag
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.ref }}
          regex: "^refs/tags/(.+)$"
      - name: Publish to Open VSX Registry
        id: publish_to_open_vsx
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: ${{ steps.publish_to_open_vsx.outputs.vsixPath }}
      - name: Create draft release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions.
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.parse_tag.outputs.group1 }}
      - name: Upload packages to release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.publish_to_open_vsx.outputs.vsixPath }}
          asset_content_type: application/vsix
